language: node_js
node_js:
    - 12
services:
    - docker

before_install:
    - docker build -t $DOCKER_ID/fibonacci-client-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true $DOCKER_ID/fibonacci-client-test yarn test


after_success:
    - docker build -t $DOCKER_ID/fibonacci-client ./client
    - docker build -t $DOCKER_ID/fibonacci-server ./server
    - docker build -t $DOCKER_ID/fibonacci-worker ./worker
    - docker build -t $DOCKER_ID/fibonacci-nginx ./nginx

    # Login to docker-hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker-hub
    - docker push $DOCKER_ID/fibonacci-client
    - docker push $DOCKER_ID/fibonacci-server
    - docker push $DOCKER_ID/fibonacci-worker
    - docker push $DOCKER_ID/fibonacci-nginx

deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    app: "fibonacci-saas"
    env: "FibonacciSaas-env"
    region: "us-east-1" 
    bucket_name: "elasticbeanstalk-us-east-1-888433145158"
    on:
        branch: master