version: '3'
services:
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '3050:80'
    postgres:
        image: postgres:12.3
        restart: always
        environment: 
            - POSTGRES_PASSWORD=postgres_passwoord
    redis:
        image: redis:6-alpine
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - ./server:/usr/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_PASSWORD=postgres_passwoord
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_DB=postgres
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        environment: 
            - CI=true
        volumes:
            - /usr/app/node_modules
            - ./client:/usr/app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes: 
            - /usr/app/node_modules
            - ./worker:/usr/app